
name: Deploy Markdown with Pandoc

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last updated date
        id: lastmod
        run: |
          echo "date=$(git log -1 --format=%cd --date=format:'%-d %B %Y')" >> $GITHUB_OUTPUT

      - name: Get first commit date
        id: firstdate
        run: |
          echo "date=$(git log --reverse --format=%cd --date=format:'%Y' | head -n 1)" >> $GITHUB_OUTPUT


      - name: Get repository license
        id: license
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LICENSE_NAME=$(gh api repos/${{ github.repository }} --jq '.license.name')
          LICENSE_HTML="https://github.com/${{ github.repository }}/blob/main/LICENSE"

          echo "name=$LICENSE_NAME" >> $GITHUB_OUTPUT
          echo "url=$LICENSE_HTML" >> $GITHUB_OUTPUT


      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert Markdown to styled HTML
        run: |
          pandoc essay.md \
            --standalone \
            --template=assets/template/template.html \
            --citeproc \
            --csl=https://www.zotero.org/styles/apa \
            --toc \
            --metadata last_updated="${{ steps.lastmod.outputs.date }}" \
            --metadata repo_url="https://github.com/${{ github.repository }}" \
            --metadata edit_url="https://github.com/${{ github.repository }}/blob/main/essay.md" \
            --metadata repo_name="${{ github.repository }}" \
            --metadata year_first_published="${{ steps.firstdate.outputs.date }}" \
            --metadata license_name="${{ steps.license.outputs.name }}" \
            --metadata license_url="${{ steps.license.outputs.url }}" \
            --output=index.html

          # Wrap content with GitHub-style container
          sed -i 's/<body>/<body><article class="markdown-body" style="max-width:980px;margin:0 auto;padding:45px;">/' index.html
          sed -i 's/<\/body>/<\/article><\/body>/' index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
